---
version: "3"
services:
  app:
    build: .
    volumes:
      - ./pages:/app/pages
      - ./public:/app/public
    ports:
      - 3000:3000
    env_file: .env
    command: node --require next-logger server.js

